import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'

import '../styles/globals.css'

const manrope = Manrope({ subsets: ['latin'] })

interface RootLayoutProps {
    children: ReactNode
}

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            <body className={`bg-black ${manrope.className}`}>
                <div className="w-full min-h-screen text-white scroll-smooth">
                    {children}
                </div>
            </body>
        </html>
    )
}
